name: Build Task

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    build-linux:
        name: Linux Build
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential
        - name: Build Project
          run: make
        
        - name: Run
          run: ./syncio
        
        - name: Upload build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: build-artifacts
            path: ./build