name: Build Task

on:
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build.yml'
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build.yml'

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: gcc build.c -o build.out
    - name: Build Project
      run: ./build.out
    - name: Run
      run: ./Syncio.exe

  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest'

      - name: Build
         run: cl /Fe:build.exe build.c
      - name: Run 
        run: build.exe