name: Build Task

on:
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build.yml'
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build.yml'

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependency
      run: sudo apt update && sudo apt-get install gcc libjson-c-dev
    - name: Build
      run: gcc -o CBuild.exe build.c
    - name: Build Project
      run: ./CBuild.exe syncio
    - name: Run
      run: ./Syncio.exe
