name: Build Task

on:
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build.yml'
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/**
      - '!.github/workflows/build.yml'

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: gcc build.c -o build.out
    - name: Build Project
      run: ./build.out
    - name: Run
      run: ./Syncio.exe
