on:
  pull_request:
    branches: [ "master" ]
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - .github/**
      - '!.github/workflows/build.yml'

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Project
      run: make

  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install MSYS2 and MinGW
      run: |
        choco install msys2
        msys2 -c "pacman -Sy --noconfirm mingw-w64-x86_64-gcc"
    
    - name: Add MinGW to PATH
      run: |
        echo "C:\tools\msys64\mingw64\bin" >> $env:GITHUB_PATH
    
    - name: Build Project 
      run: build.bat
