name: Build Task

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: gcc build.c -o build.out
    - name: Build Project
      run: ./build.out
    - name: Run
      run: ./Syncio.exe
