name: Build Task

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - .github/**
      - '!.github/workflows/build.yml'

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Project
      run: make
