name: Build Task

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh main.cpp
    - name: Run
      run: ./Syncio
