name: Update Changelog on Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update changelog
        run: |
          echo "## ${{ github.event.release.tag_name }} - ${{ github.event.release.published_at }}" >> CHANGELOG.md
          echo "${{ github.event.release.body }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update changelog for release ${{ github.event.release.tag_name }}" || echo "No changes to commit"

      - name: Push changes
        run: git push origin HEAD:${{ github.ref }}
